<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EstudianteController;
use App\Http\Controllers\EspecialidadesController;
use App\Http\Controllers\AdministradorController;
use App\Http\Controllers\AreaController;
use App\Http\Controllers\CarreraController;
use App\Http\Controllers\ProfesorController;
use App\Http\Controllers\PostgradoController;
use App\Http\Middleware\CheckRole;

Route::get(("/administrador"), [AdministradorController::class, 'index'])->middleware('auth','role:administrador')->name(name: 'administrador.index');
Route::get('/administrador/gestionestudiantes', [EstudianteController::class, 'list'])->name('administrador.gestionestudiantes');
Route::get(("/administrador/gestion_estudiante"), [EstudianteController::class, 'list'])->middleware('auth','role:administrador')->name('estudiante.list');
Route::get(("/administrador/registro_estudiante"), [EstudianteController::class, 'create'])->middleware('auth','role:administrador')->name('registro_estudiante.index');
Route::post(("/administrador/registro_estudiante"), [EstudianteController::class, 'store'])->middleware('auth','role:administrador')->name('estudiante.store');
Route::get(("/administrador/areas"), [AdministradorController::class, 'creacionArea'])->middleware('auth','role:administrador')->name('administrador.creacion.index');
Route::post(("/administrador/areas"), [AreaController::class, 'store'])->middleware('auth','role:administrador')->name('administrador.area.store');
Route::get(("/administrador/areas/{area}/edit"), [AreaController::class, 'edit'])->middleware('auth','role:administrador')->name('administrador.area.edit');
Route::put(("/administrador/areas/{area}"), [AreaController::class, 'update'])->middleware('auth','role:administrador')->name('administrador.area.update');
Route::delete(("/administrador/areas/{area}"), [AreaController::class, 'destroy'])->middleware('auth','role:administrador')->name('administrador.area.destroy');
Route::post("/administrador/carrera", [CarreraController::class, 'store'])->middleware('auth','role:administrador')->name('administrador.carrera.store');
Route::get("administrador/carrera/{carrera}/edit", [CarreraController::class, 'edit'])->middleware('auth','role:administrador')->name('administrador.carrera.edit');
Route::put("administrador/carrera/{carrera}", [CarreraController::class, 'update'])->middleware('auth','role:administrador')->name('administrador.carrera.update');
Route::delete("administrador/carrera/{carrera}", [CarreraController::class, 'destroy'])->middleware('auth','role:administrador')->name('administrador.carrera.destroy');
Route::post("/administrador/especialidad", [EspecialidadesController::class, 'store'])->middleware('auth','role:administrador')->name('administrador.especialidad.store');
Route::get("administrador/especialidad/{especialidad}/edit", [EspecialidadesController::class, 'edit'])->middleware('auth','role:administrador')->name('administrador.especialidad.edit');
Route::put("administrador/especialidad/{especialidad}", [EspecialidadesController::class, 'update'])->middleware('auth','role:administrador')->name('administrador.especialidad.update');
Route::delete("administrador/especialidad/{especialidad}", [EspecialidadesController::class, 'destroy'])->middleware('auth','role:administrador')->name('administrador.especialidad.destroy');
Route::get("/administrador/gestion_profesor", [ProfesorController::class, 'index'])->middleware('auth','role:administrador')->name('administrador.gestion_profesor');
Route::get("/administrador/gestion_profesor/create", [ProfesorController::class, 'create'])->middleware('auth','role:administrador')->name('administrador.gestion_profesor.create');
Route::post("/administrador/gestion_profesor", [ProfesorController::class, 'store'])->middleware('auth','role:administrador')->name('administrador.gestion_profesor.store');
Route::get("/administrador/gestion_profesor/{profesor}/edit", [ProfesorController::class, 'edit'])->middleware('auth','role:administrador')->name('administrador.gestion_profesor.edit');
Route::put("/administrador/gestion_profesor/{profesor}", [ProfesorController::class, 'update'])->middleware('auth','role:administrador')->name('administrador.gestion_profesor.update');
Route::delete("/administrador/gestion_profesor/{profesor}", [ProfesorController::class, 'destroy'])->middleware('auth','role:administrador')->name('administrador.gestion_profesor.destroy');
Route::get("/administrador/gestion_estudiante/{estudiante}/edit", [EstudianteController::class, 'edit'])->middleware('auth','role:administrador')->name('administrador.gestion_estudiante.edit');
Route::put("/administrador/gestion_estudiante/{estudiante}", [EstudianteController::class, 'update'])->middleware('auth','role:administrador')->name('administrador.gestion_estudiante.update');
Route::delete("/administrador/gestion_estudiante/{estudiante}", [EstudianteController::class, 'destroy'])->middleware('auth','role:administrador')->name('administrador.gestion_estudiante.destroy');
Route::get("/administrador/gestion_postgrado", [PostgradoController::class, 'index'])->middleware('auth','role:administrador')->name('administrador.gestion_postgrado');
Route::get("/administrador/gestion_postgrado/create", [PostgradoController::class, 'create'])->middleware('auth','role:administrador')->name('administrador.gestion_postgrado.create');
Route::post("/administrador/gestion_postgrado", [PostgradoController::class, 'store'])->middleware('auth','role:administrador')->name('administrador.gestion_postgrado.store');
Route::get("/administrador/gestion_postgrado/{postgrado}/edit", [PostgradoController::class, 'edit'])->middleware('auth','role:administrador')->name('administrador.gestion_postgrado.edit');
Route::delete("/administrador/gestion_postgrado/{postgrado}", [PostgradoController::class, 'destroy'])->middleware('auth','role:administrador')->name('administrador.gestion_postgrado.destroy');
Route::put("/administrador/gestion_postgrado/{postgrado}", [PostgradoController::class, 'update'])->middleware('auth','role:administrador')->name('administrador.gestion_postgrado.update');