<x-layout title='PostUDO || Registro de Evaluación'>
    <section class="login-page-container">
        <div class="registration-form">
            <h2 class="registration-form-title">Registro de Evaluación</h2>

            {{-- Assuming a route for storing evaluations --}}
            <form action="{{ route('profesor.gestionevaluacion.store') }}" method="POST">
                @csrf

                {{-- The id_evaluacion is usually auto-generated by the database, so it's not included as an input field here. --}}
                
                <div class="form-group">
                    <label for="titulo" class="form-label">Título de la Evaluación</label>
                    <input type="text" id="titulo" name="titulo" class="form-input" placeholder="Ej: Examen Parcial I" required>
                </div>

                <div class="form-group">
                    <label for="porcentaje" class="form-label">Porcentaje</label>
                    <input type="number" id="porcentaje" name="porcentaje" class="form-input" placeholder="Ej: 25" min="0" max="100" required>
                </div>

                <div class="form-group">
                    <label for="metodologia" class="form-label">Metodología</label>
                    {{-- Changed from select to text input as requested --}}
                    <input type="text" id="metodologia" name="metodologia" class="form-input" placeholder="Ej: Examen, Proyecto, Exposición" required>
                </div>

                <div class="form-group">
                    <label for="fecha" class="form-label">Fecha de Realización</label>
                    <input type="date" id="fecha" name="fecha" class="form-input" required>
                </div>
                
                <div class="form-actions" style="justify-content: center;">
                    <button type="submit" class="submit-button">Registrar Evaluación</button>
                </div>
            </form>
        </div>
    </section>
</x-layout>
